(define (problem test3)
    (:domain besco)
	(:objects   aa ab ac ad ae af 
	            ba bb bc bd be bf 
	            ca cb cc cd ce cf 
	            da db dc dd de df 
	            ea eb ec ed ee ef 
	            fa fb fc fd fe ff 
	            X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11 X12 X13 
	            C1 C2 C3 
	            S1 S2)
				
	(:goal (and (at C1 af) (at C2 ce) (at C3 fe)))
	(:init  
  
		(wall X1) (at X1 ab)
		(wall X2) (at X2 bb)
		(wall X3) (at X3 cb)
		(wall X4) (at X4 db)
		(wall X5) (at X5 eb)
		(wall X6) (at X6 bd)
		(wall X7) (at X7 dd)
		(wall X8) (at X8 ed)
		(wall X9) (at X9 fd)
		(wall X10) (at X10 cf)
		(wall X11) (at X11 df)
		(wall X12) (at X12 ef)
		(wall X13) (at X13 ff)
		
		(sentinel S1) (at S1 aa)
		(sentinel S2) (at S2 ba)
		
		(box C1) (at C1 ae)
		(box C2) (at C2 be)
		(box C3) (at C3 ee)

		(isup aa ba) 
		(isup ba ca) 
		(isup ca da) 
		(isup da ea) 
		(isup ea fa) 
				  
		(isup ab bb) 
		(isup bb cb)
		(isup cb db) 	 
		(isup db eb) 	 
		(isup eb fb) 	 
				  
		(isup ac bc) 
		(isup bc cc) 
		(isup cc dc) 
		(isup dc ec) 
		(isup ec fc) 
				  
		(isup ad bd)
		(isup bd cd)
		(isup cd dd)
		(isup dd ed)
		(isup ed fd)
				
		(isup ae be)
		(isup be ce)
		(isup ce de)
		(isup de ee)
		(isup ee fe)
		
		(isup af bf)
		(isup bf cf)
		(isup cf df)
		(isup df ef)
		(isup ef ff)

		(isright ab aa)
		(isright bb ba)
		(isright cb ca)
		(isright db da)
		(isright eb ea)
		(isright fb fa)

		(isright ac ab)
		(isright bc bb)
		(isright cc cb)
		(isright dc db)
		(isright ec eb)
		(isright fc fb)

		(isright ad ac)
		(isright bd bc)
		(isright cd cc)
		(isright dd dc)
		(isright ed ec)
		(isright fd fc)
		
		(isright ae ad)
		(isright be bd)
		(isright ce cd)
		(isright de dd)
		(isright ee ed)
		(isright fe fd)
		
		(isright af ae)
		(isright bf be)
		(isright cf ce)
		(isright df de)
		(isright ef ee)
		(isright ff fe)
		
		(block aa)
		(block ab)  
		(block ac)  (empty ac)
		(block ad)  (empty ad)
		(block ae)  
		(block af)  (empty af)
		(block ba) 
		(block bb)  
		(block bc)  (empty bc)
		(block bd)  
		(block be)  
		(block bf)  (empty bf)
		(block ca)  (empty ca)
		(block cb)  
		(block cc)  (empty cc)
		(block cd)  (empty cd)
		(block ce)  (empty ce)
		(block cf)  
		(block da)  (empty da)
		(block db)  
		(block dc)  (empty dc)
		(block dd)		
		(block de)  (empty de)
		(block df)  
		(block ea)  (empty ea)
		(block eb)  
		(block ec)  (empty ec)
		(block ed)	
		(block ee)  
		(block ef)  
		(block fa)  (empty fa)
		(block fb)  (empty fb)
		(block fc)  (empty fc)
		(block fd)	
		(block fe)  (empty fe)
		(block ff) 
	
	 ))